# Generated by Django 4.0.2 on 2022-03-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_product_review_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
